Repository arendst/Tasmota, pull requests merged in 2019-04, with the labels that each got.

#5584 MiDesk Lamp not default activated
  sonoff/my_user_config.h
  sonoff/sonoff.ino
  sonoff/sonoff_template.h
  sonoff/support_rotary.ino
Labels: Requires more research (devs)

#5667 Support for color and colortone in Philips Hue emulation via Alexa
  sonoff/_changelog.ino
  sonoff/xdrv_04_light.ino
  sonoff/xplg_wemohue.ino
Labels: awaiting feedback

#5684 Change tele message of ADS1115 to allow it to work correctly with rules
  sonoff/xsns_12_ads1115.ino
Labels: enhancement
