Repository arendst/Tasmota, pull requests merged in 2019-02, with the labels that each got.

#5083 add functionality to use multiple ads1115's on one i2cbus
  sonoff/xsns_12_ads1115.ino
  sonoff/xsns_16_tsl2561.ino
Labels: awaiting for feedback, enhancement

#4991 Add support for the SM16716 RGB LED controller
  sonoff/language/bg-BG.h
  sonoff/language/cs-CZ.h
  sonoff/language/de-DE.h
  sonoff/language/el-GR.h
  sonoff/language/en-GB.h
  sonoff/language/es-AR.h
  sonoff/language/fr-FR.h
  sonoff/language/he-HE.h
  sonoff/language/hu-HU.h
  sonoff/language/it-IT.h
  sonoff/language/nl-NL.h
  sonoff/language/pl-PL.h
  sonoff/language/pt-BR.h
  sonoff/language/pt-PT.h
  sonoff/language/ru-RU.h
  sonoff/language/sk-SK.h
  sonoff/language/sv-SE.h
  sonoff/language/tr-TR.h
  sonoff/language/uk-UK.h
  sonoff/language/zh-CN.h
  sonoff/language/zh-TW.h
  sonoff/my_user_config.h
  sonoff/sonoff.h
  sonoff/sonoff.ino
  sonoff/sonoff_template.h
  sonoff/support_features.ino
  sonoff/xdrv_04_light.ino
Labels: enhancement

#5242 Remove wifi password restriction
  sonoff/i18n.h
  sonoff/xdrv_01_webserver.ino
Labels: awaiting feedback, enhancement

#5202 Correct rounding for ws2812 clock mode shifting hour when pixel<60
  sonoff/xplg_ws2812.ino
Labels: Requires testing
