Repository arendst/Tasmota, pull requests merged in 2019-11, with the labels that each got.

#6812 Tasmota slave
  tasmota/xdrv_31_tasmota_slave.ino
Labels: enhancement

#6815 TasmotaSlave: Bugfix
  tasmota/xdrv_31_tasmota_slave.ino
Labels: bug, fixed

#6903 Fix INA226 JSON in ID field
  tasmota/xsns_54_ina226.ino
Labels: awaiting feedback
